#include <fstream>
#include <cstdint>
#include <string>
#include <stdexcept>

#include "line_inter.hpp"
#include "include/float32_array_utils_tb.h"
#include "include/streamutils_tb.h"

int main(int argc, char** argv) {
    const std::string data_dir = (argc > 1) ? argv[1] : "data";

    // Read the input test data for the command header from files generated by the Python testbench
    CmdHdr cmd_hdr;
    streamutils::read_uint32_file(cmd_hdr, (data_dir + "/cmd_hdr_data.bin").c_str());

    // Read the input test data for the samples from files generated by the Python testbench
    const int nsamp = cmd_hdr.nsamp;
    float x[max_nsamp][ndim] = {};
    float dsq_dut[max_nsamp] = {};
    float dsq_exp[max_nsamp] = {};
    float32_array_utils::read_uint32_file_array(&x[0][0], (data_dir + "/x_in_data.bin").c_str(), 
        nsamp * ndim);

    // Read the expected output data for the sample payload from files generated by the Python testbench
    float32_array_utils::read_uint32_file_array(dsq_exp, (data_dir + "/dsq_exp.bin").c_str(), nsamp);

    // Create AXI4-Stream interfaces
    hls::stream<axis_word_t> in_stream;
    hls::stream<axis_word_t> out_stream;

    // Push the command header as its own TLAST-terminated burst.
    cmd_hdr.write_axi4_stream<WORD_BW>(in_stream, true);

    // Push the sample payload as a second TLAST-terminated burst. 
    float32_array_utils::write_axi4_stream<WORD_BW>(in_stream, &x[0][0], true, nsamp * ndim);
    
    // Run the accelerator
    line_inter(in_stream, out_stream);

    // Read the response header
    RespHdr resp_hdr;
    streamutils::tlast_status resp_hdr_tlast = streamutils::tlast_status::no_tlast;
    resp_hdr.read_axi4_stream<WORD_BW>(out_stream, resp_hdr_tlast);

    // Read the output sample payload
    streamutils::tlast_status samp_out_tlast = streamutils::tlast_status::no_tlast;
    float32_array_utils::read_axi4_stream<WORD_BW>(out_stream, dsq_dut, samp_out_tlast, nsamp);

    // Read the response footer
    RespFtr resp_ftr;
    streamutils::tlast_status resp_ftr_tlast = streamutils::tlast_status::no_tlast;
    resp_ftr.read_axi4_stream<WORD_BW>(out_stream, resp_ftr_tlast);

    // Measure the MAE
    float mae = 0.f;
    for (int i = 0; i < nsamp; ++i) {
        mae += std::abs(dsq_dut[i] - dsq_exp[i]);
    }
    mae /= nsamp;
    std::cout << "MAE: " << mae << std::endl;

    // Write the output files
    streamutils::write_uint32_file(resp_hdr, (data_dir + "/resp_hdr_data.bin").c_str());
    float32_array_utils::write_uint32_file_array(dsq_dut, (data_dir + "/dsq_dut.bin").c_str(), nsamp);
    streamutils::write_uint32_file(resp_ftr, (data_dir + "/resp_ftr_data.bin").c_str());

    std::ofstream sync_ofs(data_dir + "/sync_status.json");
    if (!sync_ofs) {
        throw std::runtime_error("Failed to open sync_status.json for writing.");
    }
    sync_ofs
        << "{\n"
        << "  \"resp_hdr_tlast\": \"" << streamutils::to_string(resp_hdr_tlast) << "\",\n"
        << "  \"samp_out_tlast\": \"" << streamutils::to_string(samp_out_tlast) << "\",\n"
        << "  \"resp_ftr_tlast\": \"" << streamutils::to_string(resp_ftr_tlast) << "\"\n"
        << "}\n";

    return 0;
}
